version: '3.8'

networks:
  wodo_gamehub:
    name: 'wodo_gamehub'

services:
  nginx:
    build:
      context: ./docker-dev
      dockerfile: docker-dev/nginx.dockerfile
    container_name: nginx
    depends_on:
      - php
      - mysql
      - redis
    ports:
      - "8000:80"
#      - "4433:443"
    volumes:
      - ./:/var/www/html
    networks:
      - wodo_gamehub

  php:
    build:
      context: ./docker-dev
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
    networks:
      - wodo_gamehub

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "4306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wodo_gamehub
      MYSQL_USER: wodo
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - wodo_gamehub

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - wodo_gamehub


  artisan:
    build:
      context: docker-dev
      dockerfile: php.dockerfile
    container_name: artisan
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan"]
    networks:
      - wodo_gamehub

  npm:
    image: node:18-alpine
    container_name: npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - wodo_gamehub


  phpunit:
    build:
      context: ./docker-dev
      dockerfile: php.dockerfile
    container_name: phpunit
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["/var/www/html/vendor/bin/phpunit"]
    networks:
      - wodo_gamehub

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    networks:
      - wodo_gamehub

  scheduler:
    build:
      context: ./docker-dev
      dockerfile: php.dockerfile
    container_name: scheduler
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan", "schedule:work"]
    networks:
      - wodo_gamehub

  soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    container_name: soketi
    environment:
      DEBUG: '1'
      METRICS_SERVER_PORT: '9601'
    ports:
      - '${SOKETI_PORT:-6001}:6001'
      - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
    networks:
      - wodo_gamehub
