#!/usr/bin/env bash

# Run PHP-FPM as current user
sed -i "s/user\ \=.*/user\ \= 1000/g" /etc/php/8.1/fpm/pool.d/www.conf
# Set UID of user "ubuntu"
usermod -u 1000 ubuntu

# Ensure /.composer exists and is writable
if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

# if we passed a command, then run it
if [ $# -gt 0 ]; then
    exec gosu 1000 "$@"
else
  # Else default to supervisord
  /usr/bin/supervisord
fi

